name: clean_architecture_posts_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # functional programming things
  dartz: ^0.10.1
  # Value equality (objects comparison)
  equatable: ^2.0.3
  # Service locator (dependencies injection)
  get_it: ^7.2.0
  # Remote API
  internet_connection_checker: ^0.0.1+3
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.13 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


